### ISSUE TITLE
Обработка ошибок подключения

### ISSUE THREAD

**Issue by volkov** [ElizavetaP/python_mysql#10]
При запуске приложения получаю что то вроде:

```
Traceback (most recent call last):
  File "MySQL_2_7_09.py", line 11, in <module>
    db = config.get('mysql', 'db'))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'meteouser'@'localhost' (using password: YES)")

```

Хочется что бы ошибка была читаема, напримет только сам текст

```
Access denied for user 'meteouser'@'localhost' (using password: YES)
```

**Comment by volkov** [comment]
А после того как база создана я получаю

```
Traceback (most recent call last):
  File "MySQL_2_7_09.py", line 24, in <module>
    if sys.argv[1] == 'import':
IndexError: list index out of range
```

Стоит писать список комманд т.к. их иначе не узнать не глядя в код.

---

откуда такая ошибка?

нужно писать описание режимов?

**Comment by volkov** [comment]
```
$ python MySQL_2_7_09.py site
```

Отрабатывает без какого либо вывода на экран, что произошло не понятно, имеет смысл печатать полученные данные

**Comment by volkov** [comment]
```
$ python MySQL_2_7_09.py asdfasdfadsfa
```

тоже ничего не говорит, хотя это похоже на ошибку

**Comment by volkov** [comment]
Ошибка возникает при запуске без параметров

```
$ python MySQL_2_7_09.py
```

Да, стоит писать возможные режимы.

**Comment by ElizavetaP** [comment]
Ошибка возникает при запуске без параметров

$ python MySQL_2_7_09.py

Да, стоит писать возможные режимы.

так у меня это уже сделано
